#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091

source /scripts/common

if ! chk_enabled "${AIRSPY_ADSB_STATS}"; then
    stop_service
fi

exec s6wrap --quiet --prepend=nginx --timestamps --args /usr/sbin/nginx
